### ISSUE TITLE
can it be trained with gpu?

### ISSUE THREAD

**Issue by lijiajia** [cerndb/dist-keras#10]
Hi, can this framework be trained with gpus?

**Comment by JoeriHermans** [comment]
In theory yes, just follow the Keras documentation https://keras.io/getting-started/faq/#how-can-i-run-keras-on-gpu

However, I would say that it might cause problems when Spark schedules more than 1 executor on the same compute node. However, if this does not happen it should be fine. Of course, this is just my intuition, I still have to test this.
