### ISSUE TITLE
Ambiguous reference in notebook workflow

### ISSUE THREAD

**Issue by quang-ha** [cerndb/dist-keras#19]
While running the workflow notebook, running cell 12 present the following error:

```
AnalysisException: u"Reference 'label' is ambiguous, could be: label#395, label#399, label#400.;"
```

Is there a work-around for the problem?

**Comment by JoeriHermans** [comment]
Did you run this cell multiple times? That would explain the duplicated columns. A workaround would be to select the original columns before executing that particular cell again.

**Comment by quang-ha** [comment]
It fails even on single run. Sorry for beginner's question, but which original column?

**Comment by JoeriHermans** [comment]
Hmmm, I really need to check this workflow notebook. I would recommend starting with the MNIST notebook. This one is pretty complete. If you need additional information on what is actually happening in the background, I recommend you to read the first chapter of my master thesis https://github.com/JoeriHermans/master-thesis/blob/master/thesis/master_thesis_joeri_hermans.pdf

**Comment by SoulGuedria** [comment]
I'm facing the same issue. Any suggestion ? Thanks

**Comment by dbl001** [comment]
'label' is duplicated.  Try changing 'label' to 'label_output' and adjust all references.

```
dataset = dataset.select("features_normalized", "label_index", "label_output")

# Show the expected output vectors of the neural network.
dataset.select("label_index", "label_output").take(1)
```
