### ISSUE TITLE
Uncaught exception on malformed feature shape

### ISSUE THREAD

**Issue by sebastianmarkow** [cerndb/dist-keras#20]
There seems to be no checks for valid input data shape on the worker side.

See [worker.py#L129](https://github.com/cerndb/dist-keras/blob/511ffce4de3ab32af703f35fca01786f8bce4b16/distkeras/workers.py#L129)

Any ideas how to handle these? I'm willing to help make this less error prone.

**Comment by JoeriHermans** [comment]
Yes, you are correct. However, having to check for data shape is wasting computational resources imho. However, one could implement a check at the start of the training procedure (defined in trainers.py).

To be honest, I usually ensure that the data is reshaped correctly before I start the training.
