### ISSUE TITLE
two calls on train_on_batch per iteration

### ISSUE THREAD

**Issue by CY-dev** [cerndb/dist-keras#23]
Hi Joeri,

Thank you for making this package available! Your package seems a promising solution for the data loading problem we are facing in our model. 

I have a question regarding different implementations of the worker class in workers.py. I suppose there should be only one call to "train_on_batch" for each batch (X, Y) in all worker subclasses, but this is the case only for ADAGWorker. For the worker subclasses implementing all the other algorithms, there are 2 calls to "train_on_batch" and only the second one is recorded in "training_history". Why?

**Comment by JoeriHermans** [comment]
Hi,

Thanks for evaluating, there is still some work to be done :)

Ouwch... I think I was being clumsy while implementing this feature. No, this is not the way it should be. The thing is I usually spent my time improving ADAG (and ExperimentalTrainer). So I do not really check other optimizers. However, I'll fix the issue you reported now.

**Comment by CY-dev** [comment]
Thanks for the quick update!

**Comment by JoeriHermans** [comment]
Fixed in https://github.com/cerndb/dist-keras/commit/283a86413969183178a95f602dcc6144957bd2d8

Thanks again for reporting this.


Kind regards,

Joeri
