### ISSUE TITLE
Transformers cause out of memory errors on executors

### ISSUE THREAD

**Issue by bensums** [cerndb/dist-keras#27]
I think this is due to `utils.new_dataframe_row` copying whole rows. Why not use a UDF in the `transform` method? I observe this while doing a count on a dataset of only 6 million rows after transforming it with `OneHotTransformer`.

**Comment by JoeriHermans** [comment]
Did you set the persistence to STORAGE_AND_MEMORY? That should resolve the issue. Remeber it doesn't copy the datagrams row as a whole, but the references + a new column and value. Furthermore, what is the dimensionality of you one hot encoded vector?
