### ISSUE TITLE
how can I solve this issue?

### ISSUE THREAD

**Issue by rayjang** [cerndb/dist-keras#34]
I really love your project and tried to use yours but I am in trouble like this.
(on Ubuntu)I downloaded spark-2.2.0-hadoop2.7 and unzip.
after that, I installed dist-keras.
I faced this error.
**"# In Windows, ensure the Java child processes do not linger after Python has exited.
Exception: Java gateway process exited before sending the driver its port number"**
at "sc = SparkContext(conf=conf)"
I did googling but I can't find the way. Can you let me know how to solve it?

**Comment by JoeriHermans** [comment]
Could you post the bootstrapping code?

Joeri

**Comment by rayjang** [comment]
I use a 'workflow' ipython file you provided.
![image](https://user-images.githubusercontent.com/9244296/31063233-2a6f195a-a76c-11e7-9333-69b6a06fd24d.png)
and I added this to .bashrc

![image](https://user-images.githubusercontent.com/9244296/31063280-96ab5a34-a76c-11e7-910a-041d739658f6.png)


only my $PATH is "/home/rayjang/anaconda3/bin:/bin:/usr/local/bin

**Comment by JoeriHermans** [comment]
Some Googling brought me to the possibility that PYSPARK_DRIVER_PYTHON etc might be the issue. Can you use a different Python? (E.g., Anaconda Python)

Let me know.

Joeri

**Comment by rayjang** [comment]
Thanks!! It was totally my fault.
I didn't set up my hadoop conf.
Sorry since I didn't read your instruction carefully

**Comment by JoeriHermans** [comment]
No problem :) If you have any other questions, feel free to post them.

Joeri
