### ISSUE TITLE
Running out of HDD

### ISSUE THREAD

**Issue by raviolli** [cerndb/dist-keras#43]
Hi, I am running out of HDD space when I use the trainer. The command from spark UI is: 
javaToPython at NativeMethodAccessorImpl.java:0 +details
RDD: *Project [features_1hot#55, labels_1hot#56] +- Scan ExistingRDD[label_index#53L,features#54,features_1hot#55,labels_1hot#56]

org.apache.spark.sql.Dataset.javaToPython(Dataset.scala:2794)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
py4j.Gateway.invoke(Gateway.java:280)
py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
py4j.commands.CallCommand.execute(CallCommand.java:79)
py4j.GatewayConnection.run(GatewayConnection.java:214)
java.lang.Thread.run(Thread.java:748)

It runs till all the nodes run out of HDD space. What's going on here? Thanks,

P.S. This happened when I set EPOCH to 5000.

**Comment by raviolli** [comment]
I believe it happens bc of the large EPOCH creates a LARGE dataset (unionAll) 

There must be a better way to EPOCH

**Comment by JoeriHermans** [comment]
Hi,

In the current version (if you pull the most recent commit from master), epoch handling is done by copying the Spark Iterators. So this is a resolved issue. However, as noted in Issue #35 this has other problems as well.

Joeri

**Comment by raviolli** [comment]
I think I installed via pip. Thanks.

**Comment by JoeriHermans** [comment]
Will update the pip repo, thanks for reminding me.

Joeri
