### ISSUE TITLE
too much stderr on workers

### ISSUE THREAD

**Issue by marty90** [cerndb/dist-keras#54]
When using ADAG, yarn logs get full of verbose text.
I guess the origin is at
https://github.com/cerndb/dist-keras/blob/04cf7767e636cf614ea1fdb98753fe79647f81db/distkeras/workers.py#L340

Is it possible to disable it? It's becoming a DOS to our cluster!
In 20 minutes I got more than 3 milion entries on my logs!

**Comment by JoeriHermans** [comment]
Pushed a fix in https://github.com/cerndb/dist-keras/commit/06c4e39954d9add3808042212a321febe21857b9 Could you verify your YARN logs with the patch?

Joeri

**Comment by marty90** [comment]
Yes,  line 340 was the killer!
Thank You!
BTW: one could add a "verbose" parameter to configure the standard output on executors. For debugging, it might useful to have such kind of output, while for production is harmful.
Ciao!

**Comment by JoeriHermans** [comment]
In principle these metrics are collected in the history object which you can collect from `trainer.get_history()` :) I'm closing this issue now, feel free to open another issue whenever you have problems.

Joeri

**Comment by marty90** [comment]
Cool! Thank you!
