### ISSUE TITLE
Regarding compatibility between Python, Tensorflow and dist-keras

### ISSUE THREAD

**Issue by anishsharma** [cerndb/dist-keras#55]
Hi JoeriHermans,

I am using **python 2.7** and have install **Keras 2.1.4**. Now when I trying to run your MNIST example, it gave me a "**ImportError: No module named tensorflow**" error. I went ahead and tried to install tensorflow via pip. I am on **Windows 10 64 bit**. As it turns out on windows, tensorflow only supports **Python 3**. So I am stuck here because in **dist-keras** description, it was mentioned that it has compatibly issues with **python 3**. I want my setup to be perfect so that I shouldn't face any issues going forward. Also, I am leaning towards **python 2.7** because of better library support. For example, the other day I was installing **Cassandra** and the server was not starting on **python 3** but work well in **python 2.7**. Please advice on how can I make **keras** and **dist-keras** work with **tensorflow** on **windows 10 64 bit** platform with **python 2.7**.

Thanks & Regards
Anish Sharma

**Comment by JoeriHermans** [comment]
The framework is compliant with Python 3. Should not give any problems. If any occur, feel free to re-open.

Joeri
