### ISSUE TITLE
something confused  about LabelIndexTransformer's code

### ISSUE THREAD

**Issue by sodaling** [cerndb/dist-keras#8]
Here is part of your LabelIndexTransformer's code:
```python
    def get_index(self, vector):
        """Returns the index with the highest value or with activation threshold."""
        for index in range(0, self.output_dimensionality):
            if vector[index] >= self.activation_threshold:
                return index
```
Returns the index with the highest value or with activation threshold.But i think it only return the first index with activation threshold.It can't return the index with the highest value.Do i misunderstand it?

**Comment by JoeriHermans** [comment]
You are right, my mistake. Do you want me to change it, or do you want to do a PR so that you are also listed as a contributor?

Thanks again.

**Comment by JoeriHermans** [comment]
Something like this maybe? If you don't have anything to add, you can use this code to do the PR

```python
def get_index(self, vector):
    """Returns the index with the highest value or with activation threshold."""
    max = 0.0
    max_index = self.default_index
    for index in range(0, self.output_dimensionality):
        if vector[index] >= self.activation_threshold:
            return index
        if vector[index] > max:
            max = vector[index]
            max_index = index

    return max_index
```

**Comment by sodaling** [comment]
I think you change it better.After all, i think i am not qualified enough to be listed as a contributor.
Thank you for your kindness!

**Comment by JoeriHermans** [comment]
I'll push the changes to master as soon as I can.

Thank you for contributing.

**Comment by sodaling** [comment]
Maybe it should changed to 
```python
def get_index(self, vector):
    """Returns the index with the highest value or with activation threshold."""
    max = 0.0
    max_index = self.default_index
    for index in range(0, self.output_dimensionality):
        if vector[index] >= self.activation_threshold:
            if vector[index] > max:
                max = vector[index]
                max_index = index

    return max_index
```

**Comment by JoeriHermans** [comment]
Patched

https://github.com/cerndb/dist-keras/commit/b0314d7b7535524c3318e5ed2f8c564f1af2cd44
